# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
  - selectors

pr:
  branches:
    include:
      - '*' # must quote since "*" is a YAML reserved character; we want a string

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: './'
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run lint'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run build:lib'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'test'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: './'
      customCommand: 'run build -- --prod'
